version: '3'

services:
  cliserver:
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://172.17.0.1:8888']
      interval: 10m
      retries: 30
      start_period: 60s
    build: .
    container_name: cliserver
    working_dir: /usr/src/app
    # command: python3 manage.py runserver 0.0.0.0:8888
    volumes:
      - .:/usr/src/app
    ports:
      - 8200:8888
